### ISSUE TITLE
Input CSV does not exist - how to solve this problem?

### ISSUE THREAD

**Issue by jsim77** [ripple/xrp-batch-payout-cli#295]
Dear Support, 

I've done the following as per the given instruction in this xrp-batch-payout-cli but I kept having the same error as mentioned in the subject title. At first, I did insert my XRP wallet address and saved it as .csv file but same error. When I try a second attempt, this time without filling any XRP wallet address, the error shows the same. Kindly refer to the copy and paste error below for your reference and easier discussion:

jsjs77@Sims-MacBook-Pro ~ % xrp-batch-payout-cli
✔ Path to input CSV? … jsjs77/Input/Input.csv
✔ Path to generate output CSV? … jsjs77/Output/Output.csv
✔ XRPL network? › Mainnet
✔ Web gRPC URL of the rippleD node? … wss://s1.ripple.com
✔ Max fee per transaction (in XRP)? … 0.01
✔ USD to XRP rate (price of 1 XRP in USD)? … 0.25
✔ Sending XRPL account secret? … *****************************
✔ Proceed with the XRP payments? … yes
ERROR 
[
  {
    code: 'custom_error',
    message: 'Input CSV does not exist.',
    path: [
      'inputCsv'
    ]
  }
]
(node:3097) UnhandledPromiseRejectionWarning: Error: 1 validation issue(s)

  Issue #0: custom_error at inputCsv
  Input CSV does not exist.

    at new ZodError (/opt/homebrew/lib/node_modules/xrp-batch-payout-cli/node_modules/zod/lib/src/ZodError.js:40:28)
    at ZodObject.parse (/opt/homebrew/lib/node_modules/xrp-batch-payout-cli/node_modules/zod/lib/src/parser.js:190:17)
    at Object.parseFromPromptToObject (/opt/homebrew/lib/node_modules/xrp-batch-payout-cli/build/src/lib/io.js:76:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async payout (/opt/homebrew/lib/node_modules/xrp-batch-payout-cli/build/src/apps/payout.js:46:29)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

- Appreciate your guidance accordingly on how to resolve the above.
Thanks.

**Comment by sappenin** [comment]
Hi @jsim77 - this looks like a simple case of having the `inputCsv` file at the wrong location -- the CLI is telling you that it can't find the file in your filesystem.

Can you try a few of these suggestions?

1. Can you verify that the CSV file is in the correct location? 
2. You might need to specify the fully-qualified filename (including directory) instead of just the file-name itself.
3. Alternatively, try placing the CSV file into the same directory that you're running the application from?
